name: Minify Assets

on:
  push:
    branches: [ main ]
    paths:
      - 'src/opengrid.js'
      - 'src/opengrid.css'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/opengrid.js'
      - 'src/opengrid.css'

jobs:
  minify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g terser
          npm install -g clean-css-cli
          
      - name: Minify JavaScript
        run: |
          terser src/opengrid.js --compress --mangle --output dist/opengrid.min.js
          
      - name: Minify CSS
        run: |
          cleancss -o dist/opengrid.min.css src/opengrid.css
          
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-minify assets [skip ci]"
          file_pattern: "dist/opengrid.min.js dist/opengrid.min.css"
